#!/bin/bash
#for n in 2 4 8 128 ; do 
for n in 4 ; do 
    for t in 1 ; do 
        for b in acc1 get put rget rput rsend send ; do 
        #for b in acc1 rmw ; do 
            qsub -t 30 -n $n --mode=c$t -O $b.$n.c$t.\$jobid ./$b.x
        done
    done
done

