#!/bin/bash 
for x in `find . -name "*.x"` ; do 
    #for n in 1 2 32 128 512 ; do 
        #for t in 1 2 4 8 16 32 64 ; do 
            n=128
            t=16
            filename=$(basename "$x")
            filename="${filename%.*}"
            echo qsub -q low -t 15 -n $n --mode=c$t -O "$filename.\\\$jobid" --env PAMID_VERBOSE=1 $x
            qsub -q low -t 15 -n $n --mode=c$t -O $filename.\$jobid --env PAMID_VERBOSE=1 $x
        #done
    #done
done
