#!/bin/bash
#PBS -N test_mpi_coll
#POOPBS -l mppwidth=64
#PBS -l walltime=0:30:00
#PBS -joe
#PBS -V
#PBS -q regular

cd ${PBS_O_WORKDIR}

#echo "PBS_NUM_NODES=${PBS_NUM_NODES}"
#echo "PBS_NUM_PPN=${PBS_NUM_PPN}"
#echo "PBS_NP=${PBS_NP}"

export MPPWIDTH="${PBS_NP}"
echo "MPPWIDTH=${MPPWIDTH}"

export MPICH_GNI_DYNAMIC_CONN=disabled

env > driver.n${MPPWIDTH}.${PBS_JOBID}.log

aprun -n ${MPPWIDTH} ./driver.x 100000000 2>&1 > driver.n${MPPWIDTH}.${PBS_JOBID}.log
